version: '3.9'

services:
# MogoDb Services
  mongo_db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
# API Services
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: api
    restart: always
    ports:
      # - 5173:5173
      - 5000:5000
    volumes:
      - ./server:/app/
      - /app/node_modules  
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: testbase
      NAME: DemoApi
    depends_on:
      - mongo_db
# Client Services
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client
    restart: always
    ports:
      - 5173:5173
    environment:
      REACT_APP_API_URL: http://localhost:5173
    depends_on:
      - api

volumes:
  mongo_db: