version: '3.9'

services:
# MogoDb Services
  mongo_db:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mern_network
    volumes:
      - mongo_db:/data/db
# API Services
  api:
    build: 
      dockerfile: Dockerfile
      context: ./server
    container_name: api
    restart: always
    ports:
      # - 5173:5173
      - 5000:5000
    networks:
      - mern_network  
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo_db:27017
      DB_NAME: testbase
      NAME: DemoApi
    depends_on:
      - mongo_db
# Client Services
  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    restart: always
    ports:
      - 3000:3000
    networks:
      - mern_network       
    environment:
      REACT_APP_API_URL: http://localhost:5173
    depends_on:
      - api
networks:
  mern_network:
    driver: bridge
volumes:
  mongo_db: