name: Deploy pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
    test-server:
        name: testing-server
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t mrclapham/fullstack-amplify-server -f server/Dockerfile.dev ./server
          - run: docker run -e CI=true mrclapham/fullstack-amplify-server npm test   
    test-client:
        name: testing-client
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t mrclapham/fullstack-amplify-client -f client/Dockerfile.dev ./client
          - run: docker run -e CI=true mrclapham/fullstack-amplify-client npm test