name: Deploy pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
    job:
        name: testing
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
          - run: docker build -t mrclapham/fullstack-amplify-server -f server/Dockerfile.dev ./server
          - run: docker run -e CI=true mrclapham/fullstack-amplify-server npm test         